In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[9365, 1522, 4234, 6196],
 [9365, 1522, 4234, 9183],
 [9365, 889, 4234, 4221],
 [361, 2286, 1106, 3377, 316],
 [361, 2286, 1106, 3377, 8753],
 [5386, 9365, 8628, 4234, 7901],
 [8883, 7723, 555, 3377]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9365 1522 4234 6196]
 [   0    0    0    0 9365 1522 4234 9183]
 [   0    0    0    0 9365  889 4234 4221]
 [   0    0    0  361 2286 1106 3377  316]
 [   0    0    0  361 2286 1106 3377 8753]
 [   0    0    0 5386 9365 8628 4234 7901]
 [   0    0    0    0 8883 7723  555 3377]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 61ms/step


array([[[-4.68231812e-02, -2.86923535e-02,  3.08437608e-02,
         -4.39460762e-02,  2.45000459e-02, -1.14710331e-02,
         -2.01572068e-02, -1.70360208e-02,  9.90896299e-03,
          2.25057267e-02],
        [-4.68231812e-02, -2.86923535e-02,  3.08437608e-02,
         -4.39460762e-02,  2.45000459e-02, -1.14710331e-02,
         -2.01572068e-02, -1.70360208e-02,  9.90896299e-03,
          2.25057267e-02],
        [-4.68231812e-02, -2.86923535e-02,  3.08437608e-02,
         -4.39460762e-02,  2.45000459e-02, -1.14710331e-02,
         -2.01572068e-02, -1.70360208e-02,  9.90896299e-03,
          2.25057267e-02],
        [-4.68231812e-02, -2.86923535e-02,  3.08437608e-02,
         -4.39460762e-02,  2.45000459e-02, -1.14710331e-02,
         -2.01572068e-02, -1.70360208e-02,  9.90896299e-03,
          2.25057267e-02],
        [-4.77434285e-02,  9.57842916e-03,  4.40209545e-02,
         -1.52215362e-05, -4.31627408e-02,  2.13418864e-02,
          1.93693303e-02, -1.53471716e-02,  3.394962